export const links = [
  { id: "01", href: "/latest", label: "Latest" },
  { id: "02", href: "/national", label: "National" },
  { id: "03", href: "/politics", label: "Politics" },
  { id: "04", href: "/countrywide", label: "Countrywide" },
  { id: "05", href: "/international", label: "World" },
  { id: "06", href: "/sports", label: "Sports" },
  { id: "07", href: "/education", label: "Education" },
  { id: "08", href: "/health", label: "Health" },
  { id: "09", href: "/opinion", label: "Opinion" },
  { id: "10", href: "/religion", label: "Religion" },
  { id: "11", href: "/crime", label: "Crime" },
  { id: "12", href: "/technology", label: "Technology" },
  { id: "13", href: "/entertainment", label: "Entertainment" },
  { id: "14", href: "/economy", label: "Economy" },
  { id: "15", href: "/law-and-justice", label: "Law & Justice" },
  { id: "16", href: "/environment", label: "Environment" },
  { id: "17", href: "/science", label: "Science" },
];
