export const links = [
  { id: "01", href: "/latest", label: "Latest" },
  { id: "02", href: "/national", label: "National" },
  { id: "03", href: "/politics", label: "Politics" },
  { id: "04", href: "/countrywide", label: "Countrywide" },
  { id: "05", href: "/international", label: "World" },
  { id: "06", href: "/sports", label: "Sports" },
  { id: "07", href: "/education", label: "Education" },
  { id: "08", href: "/health", label: "Health" },
  { id: "09", href: "/opinion", label: "Opinion" },
  { id: "10", href: "/religion", label: "Religion" },
  { id: "11", href: "/crime", label: "Crime" },
  { id: "12", href: "/technology", label: "Technology" },
  { id: "13", href: "/entertainment", label: "Entertainment" },
  { id: "14", href: "/economy", label: "Economy" },
  { id: "15", href: "/law-and-justice", label: "Law & Justice" },
  { id: "16", href: "/environment", label: "Environment" },
  { id: "17", href: "/science", label: "Science" },
  { id: "18", href: "/war", label: "War" },

  { id: "19", href: "/editorial", label: "Editorial" },
  { id: "20", href: "/investigation", label: "Investigation" },
  { id: "21", href: "/story", label: "Story" }, // or "Feature"
  { id: "22", href: "/interview", label: "Interview" },
  { id: "23", href: "/analysis", label: "Analysis" },
  { id: "24", href: "/culture", label: "Culture" },
  { id: "25", href: "/books-and-arts", label: "Books & Arts" },
  { id: "26", href: "/travel", label: "Travel" },
  { id: "27", href: "/human-rights", label: "Human Rights" }, // fixed slug
  { id: "28", href: "/business", label: "Business" },
  { id: "29", href: "/finance", label: "Finance" },
  { id: "30", href: "/ai-and-future-tech", label: "AI & Future Tech" },
  { id: "31", href: "/crisis", label: "Crisis" },

];
