export const districts = [
 { id: 1, name: "Austria", flag: "/flags/Austria.png" },
  
  { id: 3, name: "Belgium", flag: "/flags/belgium.webp" },
  { id: 4, name: "Bulgaria", flag: "/flags/bulgaria.webp" },
  { id: 5, name: "Croatia", flag: "/flags/croatia.webp" },
  { id: 6, name: "Cyprus", flag: "/flags/cyprus.jpg" },
  { id: 7, name: "CzechRepublic", flag: "/flags/czech-republic.png" },
  { id: 8, name: "Denmark", flag: "/flags/denmark.jpg" },
  { id: 9, name: "Estonia", flag: "/flags/estonia.jpeg" },
  { id: 10, name: "Finland", flag: "/flags/finland.jpg" },
  { id: 11, name: "France", flag: "/flags/france.jpg" },
  { id: 12, name: "Germany", flag: "/flags/germany.jpg" },
  { id: 13, name: "Greece", flag: "/flags/greece.webp" },
  { id: 14, name: "Hungary", flag: "/flags/hungary.png" },
  { id: 15, name: "Ireland", flag: "/flags/ireland.webp" },
  { id: 16, name: "Italy", flag: "/flags/italy.webp" },
  { id: 17, name: "Latvia", flag: "/flags/latvia.jpg" },
  { id: 18, name: "Lithuania", flag: "/flags/lithuania.jpg" },
  { id: 19, name: "Luxembourg", flag: "/flags/luxembourg.webp" },
  { id: 20, name: "Malta", flag: "/flags/malta.jpg" },
  { id: 21, name: "Netherlands", flag: "/flags/netherlands.webp" },
  { id: 22, name: "Poland", flag: "/flags/poland.jpeg" },
  { id: 23, name: "Portugal", flag: "/flags/portugal.webp" },
  { id: 24, name: "Romania", flag: "/flags/romania.png" },
  { id: 25, name: "Slovakia", flag: "/flags/slovakia.jpg" },
  { id: 26, name: "Slovenia", flag: "/flags/slovenia.jpeg" },
  { id: 27, name: "Spain", flag: "/flags/spain.svg" },
  { id: 28, name: "Sweden", flag: "/flags/swedish.png" },
  { id: 29, name: "Uk", flag: "/flags/uk.png" },
  { id: 30, name: "Switzerland", flag: "/flags/switzerland.jpg" },
  { id: 31, name: "Usa", flag: "/flags/usa.webp" },
  { id: 32, name: "Canada", flag: "/flags/canada.jpg" },
  { id: 33, name: "Australia", flag: "/flags/australia.jpg" },
  { id: 34, name: "Norway", flag: "/flags/norway.webp" },
  { id: 2, name: "Bangladesh", flag: "/flags/bangladesh.jpg" },
];
