export const districts = [
  { id: 1, name: "Bangladesh" },
  { id: 2, name: "Austria" },
  { id: 3, name: "Belgium" },
  { id: 4, name: "Bulgaria" },
  { id: 5, name: "Croatia" },
  { id: 6, name: "Cyprus" },
  { id: 7, name: "Czech Republic" },
  { id: 8, name: "Denmark" },
  { id: 9, name: "Estonia" },
  { id: 10, name: "Finland" },
  { id: 11, name: "France" },
  { id: 12, name: "Germany" },
  { id: 13, name: "Greece" },
  { id: 14, name: "Hungary" },
  { id: 15, name: "Ireland" },
  { id: 16, name: "Italy" },
  { id: 17, name: "Latvia" },
  { id: 18, name: "Lithuania" },
  { id: 19, name: "Luxembourg" },
  { id: 20, name: "Malta" },
  { id: 21, name: "Netherlands" },
  { id: 22, name: "Poland" },
  { id: 23, name: "Portugal" },
  { id: 24, name: "Romania" },
  { id: 25, name: "Slovakia" },
  { id: 26, name: "Slovenia" },
  { id: 27, name: "Spain" },
  { id: 28, name: "Sweden" }
];
